cwida/duckpgq-extension

- duckpgq/src/duckpgq/functions/tablefunctions/create_property_graph.cpp
- duckpgq/src/duckpgq/functions/tablefunctions/drop_property_graph.cpp
- test/sql/basic_match.test
- test/sql/drop_property_graph.test
- test/sql/shortest_path.test
Dropping an already dropped property graph now results in an error
> Dropping a non-existing property graph now correctly throws an error

- duckpgq/include/duckpgq/duckpgq_functions.hpp
- duckpgq/include/duckpgq/functions/tablefunctions/pgq_scan.hpp
- duckpgq/src/duckpgq/functions/tablefunctions/pgq_scan.cpp
- test/sql/get_csr_ptr.test
This PR adds a new table function to get the addresses of CSR arrays, which is the base to enable memory sharing of CSR arrays.
> added functions to get the addresses of CSR arrays

- duckpgq/src/duckpgq/functions/tablefunctions/match.cpp
- test/sql/pattern-matching/inheritance_support.test
- test/sql/snb/snb-projected.test
- test/sql/snb/snb-projected.test_slow
Fixing the inheritance for more than 2 sub categories. 
Now checks properly if &(2^`idx_sublabel`) == 2^`idx_sublabel`
> Adding a projected snb test

- test/sql/label_optional.test
Fixes #80 
The `LABEL PQG_IDENT` is now optional. If it is omitted, the graph table name will be seen as the label. This allows a more concise formulation of the property graph.
> Adding LabelOptional rule

- test/sql/create_pg/optional_edge_table_clause.test
Fixes #83 
Following the SQL/PGQ specifications, the edge table clause should be optional. So a property graph can be defined with only vertex tables.
> Change parser to make EdgeTableClause optional

- duckpgq/src/duckpgq_extension.cpp
- test/sql/with_statement_duckpgq.test
Fixes #85 
The following queries are now possible 
```sql
-FROM GRAPH_TABLE (snb_projected
MATCH (m:message)
COLUMNS (m.id)
) tmp, (SELECT id from message limit 1)
LIMIT 10;
```
```sql
-WITH message_count AS (
SELECT count(*) as m_count
FROM Message m
WHERE m.creationDate < '2010-05-27 11:16:36.013'
)
SELECT year, isComment,
CASE    WHEN m_length < 40 THEN 0
WHEN m_length < 80 THEN 1
WHEN m_length < 160 THEN 2
ELSE 3 END as lengthCategory,
count(*) as messageCount,
avg(m_length) as averageMessageLength,
sum(m_length) as sumMessageLength,
count(*) / mc.m_count as percentageOfMessages
FROM GRAPH_TABLE(snb_projected
MATCH (message:Message where message.creationDate < '2010-05-27 11:16:36.013')
COLUMNS (date_part('year', message.creationDate::TIMESTAMP) as year, message.ImageFile is NULL as …
```
> WITH statements and subqueries now seem to work

- test/sql/unnamed_graphtable.test
Fixes #89 
The graph table name is now optional, and will (for now) default to unnamed_graphtable. Once multiple graph tables are possible in a query this will be changed into unnamed_graphtable<index>.
> Make graph table name optional

- README.md
- test/sql/duckdb_columns.test
- test/sql/non_existing_table.test
- test/sql/pattern-matching/basic_match.test
- test/sql/source_keyword.test
Fixes #95 
Fixes #96 
The "source" keyword was leading to a syntax error when not used as an alias with the `AS` before it. `select 1 source` would lead to this error for instance. This was happening in the "referential_constraints" which happened when querying a table that does not exist for example. I made a PR in DuckDB https://github.com/duckdb/duckdb/pull/10848 and if it gets accepted then it will be fixed for v0.10.1.
> source keyword no longer leads to syntax error

- duckpgq/src/duckpgq/functions/tablefunctions/create_property_graph.cpp
- test/sql/create_pg/create_or_replace_pg.test
Fixes #19 
Now it's possible to `CREATE OR REPLACE PROPERTY GRAPH`, avoiding the need to first drop the property graph and then create it again in case it already exists. Using only `CREATE` with a name equal to an already existing property graph will still result in an error.
> Add support for CREATE OR REPLACE PROPERTY GRAPH

- test/python/duckpgq_test.py
Fixes: https://github.com/cwida/duckpgq-extension/issues/100 🎉
You need to explicitly load the extension in Python, which I forgot about. This PR adds a simple test that works through `make test_python`
To debug pyTest > Edit configurations > Environment variables:
Name `DUCKPGQ_EXTENSION_BINARY_PATH`
Value `~/git/duckpgq/build/debug/extension/duckpgq/duckpgq.duckdb_extension`
Working directory should be `~/git/duckpgq/test/python`
Ready for debug
> Extension now also works in python environment

- duckpgq/include/duckpgq/functions/tablefunctions/create_property_graph.hpp
- duckpgq/include/duckpgq/functions/tablefunctions/match.hpp
- duckpgq/src/duckpgq/functions/tablefunctions/create_property_graph.cpp
- duckpgq/src/duckpgq/functions/tablefunctions/match.cpp
- duckpgq/src/duckpgq_extension.cpp
- test/sql/create_pg/optional_edge_table_clause.test
- test/sql/pattern-matching/basic_match.test
- test/sql/pattern-matching/undirected_edges.test
Fixes #107
Fixes #109
Fixes #60 
A bottleneck was the edge patterns containing the `ANY` edge (`-[]-`), see IS3. Previously this resulted in a slow blockwise nested loop join. We transform it into a union on the edge table (`src, dst, * from edge_table UNION ALL dst, src, * from edge_table`), resulting in two hash joins.
> Improve performance on any directed edges

- src/duckpgq_extension.cpp
- src/functions/tablefunctions/match.cpp
- src/include/duckpgq_extension.hpp
- test/sql/multiple_graph_table_error.test
Part of #88
Only ensures a proper error is thrown instead of an internal error that crashes the program
> Error handling for multiple graph tables in single query

- scripts/set_tag.sh
- src/common.cpp
- src/duckpgq_extension.cpp
- src/functions/scalar/CMakeLists.txt
- src/functions/scalar/local_clustering_coefficient.cpp
- src/functions/tablefunctions/CMakeLists.txt
- src/functions/tablefunctions/local_clustering_coefficient.cpp
- src/functions/tablefunctions/match.cpp
- src/include/duckpgq/common.hpp
- src/include/duckpgq/compressed_sparse_row.hpp
- src/include/duckpgq/duckpgq_functions.hpp
- src/include/duckpgq/functions/tablefunctions/local_clustering_coefficient.hpp
- src/include/duckpgq/functions/tablefunctions/match.hpp
- test/sql/scalar/local_clustering_coefficient.test
Fixes #123 
Users can now calculate the local clustering coefficient using a table function `SELECT * FROM local_clustering_coefficient(<pg>, <vertex table>, <edge table>)`. 
The property graph must be registered. The vertex table must be the source table referenced by the edge table. 
Two columns are returned—the primary key column of the vertex table, and the column with the local clustering coefficient. 
The local clustering coefficient is calculated for every ID. 
The function only returns the correct result on undirected graphs. Since the edge table is always directed, we convert the edge table to be undirected in the CSR.
Joining this is a bit odd, a user has to write: `from local_clustering_coefficient(snb, person, knows), person where person.id = 37383395344409 and lcc.id = …
> Local clustering coefficient

- src/duckpgq_extension.cpp
- test/sql/explain_duckpgq.test
- test/sql/with_clause.test
Fixes #129 
This PR adds the ability to use the FROM GRAPH_TABLE inside a WITH clause. 
Couple of examples: 
```sql
WITH foo AS (
SELECT id 
FROM GRAPH_TABLE(snb MATCH (a:Person))
)
SELECT * 
FROM foo 
LIMIT 10;
WITH foo AS (
FROM GRAPH_TABLE(snb MATCH (a:Person)-[r:Knows]->(b:Person) 
COLUMNS (a.id AS id, b.id AS knows_id)
)
SELECT * 
FROM foo 
LIMIT 10;
```
> Support WITH clause GRAPH_TABLE

- src/core/functions/table/local_clustering_coefficient.cpp
- src/core/functions/table/match.cpp
- src/core/utils/compressed_sparse_row.cpp
- src/core/utils/duckpgq_bitmap.cpp
- src/include/duckpgq/core/functions/table/match.hpp
- src/include/duckpgq/core/utils/compressed_sparse_row.hpp
- src/include/duckpgq/core/utils/duckpgq_bitmap.hpp
- test/sql/path_finding/subpath_match.test
- test/sql/path_finding/undirected_paths.test
Fixes #87 
This PR adds support for path-finding on undirected edges. Building an undirected CSR and then performing MS-BFS over this CSR. It can be done both inside named subpaths and outside. 
Example query:
```sql
CREATE TABLE Student(id BIGINT, name VARCHAR);INSERT INTO Student VALUES (0, 'Daniel'), (1, 'Tavneet'), (2, 'Gabor'), (3, 'Peter'), (4, 'David');
CREATE TABLE know(src BIGINT, dst BIGINT, id BIGINT);INSERT INTO know VALUES (0,1, 10), (0,2, 11), (0,3, 12), (3,0, 13), (1,2, 14), (1,3, 15), (2,3, 16), (4,3, 17), (2, 4, 18);
```
```sql
FROM GRAPH_TABLE (pg
MATCH
o = ANY SHORTEST (a:Student WHERE a.id = 0)-[e:know]-{0,2}(b:Student)
COLUMNS (a.id as a_id, b.id as b_id, path_length(o))
)
ORDER BY a_id, b_id;
```
> Support path-finding on undirected edges

- src/core/functions/function_data/CMakeLists.txt
- src/core/functions/function_data/pagerank_function_data.cpp
- src/core/functions/scalar/CMakeLists.txt
- src/core/functions/scalar/pagerank.cpp
- src/core/functions/table/CMakeLists.txt
- src/core/functions/table/pagerank.cpp
- src/include/duckpgq/core/functions/function_data/cheapest_path_length_function_data.hpp
- src/include/duckpgq/core/functions/function_data/iterative_length_function_data.hpp
- src/include/duckpgq/core/functions/function_data/pagerank_function_data.hpp
- src/include/duckpgq/core/functions/scalar.hpp
- src/include/duckpgq/core/functions/table.hpp
- src/include/duckpgq/core/functions/table/pagerank.hpp
- test/sql/scalar/pagerank.test
Fixes #143 
This PR introduces the PageRank table function, similar to WCC and LCC. 
```sql
from pagerank(pg, node_table, edge_table)
```
Will return a table with the ID and PageRank of the ID. It uses the CSR data structure, similar to the other graph algorithms and iteratively calculates the PageRank. The current implementation is mostly single threaded. The first vector to execute the function will obtain a lock and run until converged. The next vectors do not have to perform any calculation but only get the rank for the ID. If this turns out to be bottleneck in the future, we might need to look into a parallel solution, but for now this suffices. 
The default parameters are: 
Damping factor: 0.85
Tolerance: 1e-6
Initial rank: `1/number of vertices`
A future PR might add the option to …
> PageRank table function

- src/core/functions/table/create_property_graph.cpp
- src/include/duckpgq/core/functions/table/create_property_graph.hpp
- test/sql/create_pg/create_pg_with_pk_fk.test
- test/sql/create_pg/create_property_graph.test
Fixes #41 
Duckdb-pgq changes: https://github.com/cwida/duckdb-pgq/pull/203
This PR introduces more concise syntax during property graph creation if a primary key - foreign key relationship has already been defined between the vertex and edge tables. 
For the following schema: 
```sql
CREATE OR REPLACE TABLE a (
id BIGINT PRIMARY KEY,
name VARCHAR
);
CREATE OR REPLACE TABLE b (
id BIGINT PRIMARY KEY,
description VARCHAR
);
CREATE TABLE edge_ab (
id BIGINT PRIMARY KEY,
src BIGINT REFERENCES a(id),
dst BIGINT REFERENCES b(id)
);
```
The following now suffices: 
```sql
CREATE PROPERTY GRAPH g_relationship
VERTEX TABLES (a, b)
EDGE TABLES (edge_ab SOURCE a DESTINATION b);
```
Previously, the pk-fk relationship was still required to be repeated for both the source and destination, even if it …
> Implicitly defined source and destination keys

- src/core/utils/duckpgq_utils.cpp
- test/sql/scalar/local_clustering_coefficient.test
- test/sql/scalar/weakly_connected_component.test
Fixes #148 
PR for DuckDB-PGQ: https://github.com/cwida/duckdb-pgq/pull/204
This PR improves the error messages if an unknown label was used in one of the graph table functions. Need to refactor the match statement to also use this in a future PR.
Documentation page has been updated as well: https://duckpgq.notion.site/Graph-functions-c6678b8a9a9a4bd7ab42166aa727bace?pvs=74
Example error for a spelling mistake:
`Invalid Error: Label 'kows' not found. Did you mean the edge label 'knows'?`
Suggestions take into account whether we are looking for a vertex label or an edge label. 
Also in case you use the table name, while a label (which is different) is used, a user should use the label instead: 
`Invalid Error: Table 'edges' found in the property graph, but does not have the correct label. …
> Improved error messages for incorrect labels

- test/sql/path_finding/top_k.test
Fixes https://github.com/cwida/duckpgq-extension/issues/46
This PR only fixes the segmentation fault users could get when trying top k queries with slightly incorrect syntax, such as the example query in the abovementioned issue. 
We do not yet support TopK queries.
> Fix segmentation fault when doing top k queries

- src/core/functions/table/create_property_graph.cpp
- src/core/functions/table/drop_property_graph.cpp
- src/core/parser/duckpgq_parser.cpp
- src/duckpgq_extension.cpp
- src/duckpgq_state.cpp
- src/include/duckpgq_extension.hpp
- src/include/duckpgq_extension_callback.hpp
- src/include/duckpgq_state.hpp
- test/sql/create_pg/all_properties.test
- test/sql/create_pg/create_pg_multiple_connections.test
Fixes #97 
Property graphs are now persistent rather than transient. When a connection registers a property graph, it’s stored in the __duckpgq_internal table (I’m betting people won’t use this table name, though future me might regret it!). Any new connection will automatically register all property graphs stored in __duckpgq_internal. Additionally, dropping a property graph now removes it across all connections.
> Make property graphs persistent

- src/core/functions/scalar/iterativelength.cpp
- src/core/functions/scalar/shortest_path.cpp
- test/sql/path_finding/edgeless_graph.test
Fixes #163 
With an edgeless graph, we don't "initialize" the edge array in the CSR, because there is nothing to initialize. This caused an error to be thrown when doing the path-finding UDFs but that error was unnecessary. 
This PR allows the path-finding to be done on the edgeless graph.
> Allow path finding on edgeless graphs

- .github/workflows/_extension_deploy.yml
- test/sql/path_finding/kleene_star.test
Fixes #146 
Related PR: https://github.com/cwida/duckdb-pgq/pull/205
This PR fixes the bug that required a space between the (`*` or `+`) and `->`.
> Allow kleene star without a space

- src/core/functions/table/create_property_graph.cpp
- test/sql/create_pg/attach_pg.test
Previously, it was possible to get a segmentation fault if the catalog that you tried to create a property graph over did not exist. This PR should fix that. 
Also fixes some incorrect usage of schema_name, using catalog_name now instead
> Add some missing error handling for attached databases

- README.md
See issue comment https://github.com/cwida/duckpgq-extension/issues/179#issuecomment-2545020119, I personally think it's better to add some clarification at project `README` doc :)
> Add readme on query prefix

- src/core/functions/scalar/local_clustering_coefficient.cpp
- src/core/functions/scalar/weakly_connected_component.cpp
- src/core/parser/duckpgq_parser.cpp
Met some warnings during compilation, this PR fix them all.
Most of the warning here are caused by comparison between signed and unsigned integers.
> [easy] Address some compilation warnings

- src/core/CMakeLists.txt
- src/core/module.cpp
- src/core/pragma/CMakeLists.txt
- src/core/pragma/show_property_graphs.cpp
- src/include/duckpgq/core/pragma/duckpgq_pragma.hpp
- test/sql/pragma/show_property_graphs.test
This PR introduces the first pragma to the extension: 
`pragma show_property_graphs` which executes the query: `select distinct property_graph from __duckpgq_internal`. It returns all the registered property graphs in the table. Similar to `show tables`
> Add pragma show_property_graphs

- src/core/functions/scalar/local_clustering_coefficient.cpp
- src/core/functions/table/describe_property_graph.cpp
- src/core/pragma/show_property_graphs.cpp
- src/duckpgq_state.cpp
- src/include/duckpgq/core/pragma/duckpgq_pragma.hpp
- src/include/duckpgq_state.hpp
- test/sql/create_pg/create_property_graph.test
Fix issue: https://github.com/cwida/duckpgq-extension/issues/176
Tables names are case-insensitive. Example SQL to display:
```
-- Create table with lower-case.
D CREATE TABLE test_person (name TEXT);
-- Query table with upper-case.
D SELECT * FROM Test_person;
┌─────────┐
│  name   │
│ varchar │
├─────────┤
│ 0 rows  │
└─────────┘
```
This PR uses case-intensitive map to store registered property graphs.
Test result:
```
ubuntu@hjiang-devbox-pg$ ./build/debug/duckdb
v1.1.4-dev1 c380346433
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D CREATE TABLE Student(id BIGINT, name VARCHAR);
D CREATE TABLE know(src BIGINT, dst BIGINT, createDate BIGINT);
D CREATE TABLE School(school_name VARCHAR, school_id …
```
> Fix property graph case-sentisitivity

- src/core/functions/table/match.cpp
- src/include/duckpgq/core/functions/table/match.hpp
- test/sql/create_pg/attach_pg.test
- test/sql/create_pg/no_properties.test
- test/sql/path_finding/complex_matching.test
- test/sql/path_finding/shortest_path.test
Address issue https://github.com/cwida/duckpgq-extension/issues/190
The core idea for this PR is to get all columns in the property graph, and check whether the column to query is accessible or not.
> Fix query on unspecified property 

- src/core/parser/duckpgq_parser.cpp
- src/include/duckpgq/core/parser/duckpgq_parser.hpp
- test/sql/nested_subquery.test
Fixes #199 
We now also check if the `from_table` contains a `SubqueryRef`, which is then traversed to detect a potential `MATCH` statement. Before, the match wasn't found, resulting in the incorrect code path being taken. 
I've also moved the logic for `select_statements` to a separate function since the select statement and the subquery share these. 
Need to add a few more test cases before I will merge this.
> Fix segmentation fault when match was used inside subquery

- README.md
there is a link to old doc in readme
> changed link to new doc in README.md

- src/core/functions/table/create_property_graph.cpp
- src/duckpgq_state.cpp
- src/include/duckpgq/core/functions/table/create_property_graph.hpp
- test/sql/211_using_other_schemas.test
- test/sql/create_pg/attach_pg.test
- test/sql/create_pg/create_property_graph.test
- test/sql/create_pg/describe_pg.test
Fixes #211 
Related PR: https://github.com/cwida/duckdb-pgq/pull/208
Before we didn't keep proper track of the catalog and schema for the vertex and edge tables. This PR is mostly error handling and making sure we track the correct catalog and schema for all table references in the create property graph statement. Before this PR we didn't keep proper track for the source and destination tables in the definition of an edge table. So this PR also expands the `__duckpgq_internal` table with new columns: source_catalog, source_schema, destination_catalog, destination_schema.
> Allow property graph creation across different schemas

- src/core/functions/table/match.cpp
- src/include/duckpgq/core/functions/table/match.hpp
- test/sql/optional_columns.test
- test/sql/pattern_matching/inheritance_support.test
Addresses issue: https://github.com/cwida/duckpgq-extension/issues/192
The core idea for this PR is, when a star expression is met, we only include the ones include in the property graph.
> Fix star expression bind for property graph

- src/core/pragma/CMakeLists.txt
- src/core/pragma/create_vertex_table.cpp
- src/include/duckpgq/core/pragma/duckpgq_pragma.hpp
- test/sql/pragma/create_vertex_table.test
Fixes #57 
As a first implementation, this adds a pragma `create_vertex_table` that acts as a shorthand to create a vertex table from a given edge table. 
The pragma takes 5 arguments: 
* Edge table name
* Source column
* Destination column 
* Vertex table name
* ID column name (in vertex table)
The pragma executes the following query: 
```sql
CREATE TABLE v AS SELECT DISTINCT id FROM (SELECT src AS id FROM e UNION ALL SELECT dst AS id FROM e)
```
> Pragma create vertex table

- src/core/pragma/create_vertex_table.cpp
Fixes #224
The exception text mentions four required parameters, but there are five.
Update the language to "five" and include the missing parameter name (`vertex_table_name`).
> Missing parameter for `create_vertex_table` pragma

- src/core/functions/table/match.cpp
- test/sql/create_pg/all_properties.test
- test/sql/create_pg/attach_pg.test
- test/sql/path_finding/shortest_path.test
- test/sql/pattern_matching/basic_match.test
- test/sql/pattern_matching/inheritance_support.test
Fixes #228 
After introducing the restrictions on properties in the property graph creation, we have unintentionally lost some functionalities such as being able to return a table as a struct or returning all columns in a table using `alias.*`. This PR re-introduces those functionalities. Also not all properties of edge tables were returned, but not that functionality is restored as well. 
When querying `MATCH (p:Person) COLUMNS (p.*)`, we do keep in mind potential restrictions on the `Person` table defined during the property graph creation. So if `PROPERTIES (<subset of columns>)` was used, we return this subset of columns.
> Fix not being able to return table as struct and star expressions

- src/core/functions/scalar/csr_creation.cpp
- test/sql/path_finding/non-unique-vertices.test
Ran into an issue where my edge table was referring to a non existent vertex, improved the error msg to highlight this scenario.
> fix: Imporve error msg, this error was also thrown when edge tables referred to non existent vertices
